name: 🧪 Test snap can be built on x86_64

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: snapcore/action-build@v1
        id: build

      - name: Install snap and run smoke test
        run: |
          set -o pipefail
          sudo snap install --dangerous "${{ steps.build.outputs.snap }}"
          snap run --shell flightgear -c '"$SNAP/bin/fgcom" --version' 2>&1 | tee flightgear-version.txt
          snap run --shell flightgear -c 'test -d "$SNAP/fgdata" && test -x "$SNAP/usr/bin/fgfs"' \
            2>&1 | tee -a flightgear-version.txt

      - uses: diddlesnaps/snapcraft-review-action@v1
        with:
          snap: ${{ steps.build.outputs.snap }}
          isClassic: 'false'
          # Plugs and Slots declarations to override default denial (requires store assertion to publish)
          # plugs: ./plug-declaration.json
          # slots: ./slot-declaration.json

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: flightgear-smoke-test
          path: flightgear-version.txt
